insert into courses (subject, "subjectCode", "facultyId", department, program, sem, section) values
('Data Structures', 'CS-CSE-3A', 'faculty_cse_1', 'CSE', 'CSE', '3', 'A'),
('Data Structures', 'CS-CSE-3B', 'faculty_cse_1', 'CSE', 'CSE', '3', 'B'),
('Data Structures', 'CS-CSE-3C', 'faculty_cse_1', 'CSE', 'CSE', '3', 'C'),
('Data Structures', 'CS-CSE-3D', 'faculty_cse_1', 'CSE', 'CSE', '3', 'D'),
('Software Engineering', 'CS-CSD-3A', 'faculty_cse_1', 'CSE', 'CSD', '3', 'A'),
('Software Engineering', 'CS-CSD-3B', 'faculty_cse_1', 'CSE', 'CSD', '3', 'B'),
('Machine Learning', 'CS-AIML-3A', 'faculty_cse_1', 'CSE', 'AIML', '3', 'A'),
('Machine Learning', 'CS-AIML-3B', 'faculty_cse_1', 'CSE', 'AIML', '3', 'B'),
('Database Systems', 'IS-ISE-3A', 'faculty_ise_1', 'ISE', 'ISE', '3', 'A'),
('Database Systems', 'IS-ISE-3B', 'faculty_ise_1', 'ISE', 'ISE', '3', 'B'),
('Database Systems', 'IS-ISE-3C', 'faculty_ise_1', 'ISE', 'ISE', '3', 'C'),
('Database Systems', 'IS-ISE-3D', 'faculty_ise_1', 'ISE', 'ISE', '3', 'D'),
('Data Science', 'IS-CSDS-3A', 'faculty_ise_1', 'ISE', 'CSDS', '3', 'A'),
('Data Science', 'IS-CSDS-3B', 'faculty_ise_1', 'ISE', 'CSDS', '3', 'B'),
('Thermodynamics', 'ME-ME-3A', 'faculty_me_1', 'ME', 'ME', '3', 'A'),
('Thermodynamics', 'ME-ME-3B', 'faculty_me_1', 'ME', 'ME', '3', 'B'),
('Thermodynamics', 'ME-ME-3C', 'faculty_me_1', 'ME', 'ME', '3', 'C'),
('Thermodynamics', 'ME-ME-3D', 'faculty_me_1', 'ME', 'ME', '3', 'D'),
('Surveying', 'CV-CIVIL-3A', 'faculty_civil_1', 'CIVIL', 'CIVIL', '3', 'A'),
('Surveying', 'CV-CIVIL-3B', 'faculty_civil_1', 'CIVIL', 'CIVIL', '3', 'B'),
('Surveying', 'CV-CIVIL-3C', 'faculty_civil_1', 'CIVIL', 'CIVIL', '3', 'C'),
('Surveying', 'CV-CIVIL-3D', 'faculty_civil_1', 'CIVIL', 'CIVIL', '3', 'D'),
('Analog Electronics', 'EC-ECE-3A', 'faculty_ece_1', 'ECE', 'ECE', '3', 'A'),
('Analog Electronics', 'EC-ECE-3B', 'faculty_ece_1', 'ECE', 'ECE', '3', 'B'),
('Analog Electronics', 'EC-ECE-3C', 'faculty_ece_1', 'ECE', 'ECE', '3', 'C'),
('Analog Electronics', 'EC-ECE-3D', 'faculty_ece_1', 'ECE', 'ECE', '3', 'D')
on conflict do nothing;
